# Generated by Django 5.2.7 on 2025-11-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('ad', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=10)),
            ],
        ),
    ]
